### ISSUE TITLE
Should we extend this Lambda to use the "Dynamic Packages" API?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#106]
Should we extend this Lambda to use the "Dynamic Packages" API or create an _New_ Lambda which will be 95% similar except it will access the "Dynamic Packages" endpoint instead of "Classic Packages"...

see: https://docs.google.com/document/d/1x0Hp8lvyxmHNPuMugAp0LKZ4CWW8O9x4ABGZPM1qslo

**Comment by tomgco** [comment]
@nelsonic Can you explain what the differences between "Classic Packages" and "Dynamic Packages"?

**Comment by nelsonic** [comment]
@tomgco great question. Typically a "_Classic Package"_ is a _**fixed**_ offering whereas 
Dynamic packages give a lot more "_flexibility_" to trips. including:
+ Choice of flight date, time and airport
+ Flexible durations
+ Choice of accommodation
+ Variety of flights (including scheduled, charter & budget)
+ Choose from thousands of worldwide destinations 
+ Choice of board type 

From our perspective in _iSearch_ we can expect to get more results returned than from Classic API.
(_possibly an order of magnitude more results ... so we may need to keep an eye on the number of results to not overwhelm the client _)

**Comment by tomgco** [comment]
Thanks @nelsonic,

What does everyone think about consuming this API as mentioned in the documentation (once / twice) a day, place the values into Redis (keyed by hotel id) and the look up against that?

**Comment by nelsonic** [comment]
@tomgco the API docs suggest _exactly_ that (_hitting the endpoint once per day and not on every request and caching the result..._) I've been asking the same question since the start of the project. 
I _think_ that was the idea behind using "_Outbound_" API Gateway as the reverse proxy which then caches the request for as long as required. (_I suspect Redis would be a lot faster ... should we benchmark it?_)

**Comment by nelsonic** [comment]
@tomgco The only issue is caching _several_ permutations for the parameters (departure date, passengers, duration, destination). Technically there aren't _that_ many combinations, but we need to test how many there are... A pair/cluster of "**Large**" EC2 instances (7.5GB RAM) should be _ample_ to store everything tho...

**Comment by tomgco** [comment]
> @tomgco The only issue is caching several permutations for the parameters (departure date, passengers, duration, destination). Technically there aren't that many combinations, but we need to test how many there are... A pair/cluster of "Large" EC2 instances (7.5GB RAM) should be ample to store everything tho...

True, lets keep it how it is at the moment then, speaking through Outbound Proxy's.

However I do think due to the difference in packages coming back and the different code it might make sense to split these up now and set this as a goal to be a blended search.

**Comment by Kumjami** [comment]
So the options are: 
- 1 duplicationg provider database 
- 2 hit provider each time a user searchs

 
Storing full database will be useless if we need to check availability anyway. I fear I'm missing something here.

**Comment by nelsonic** [comment]
@Kumjami caching _always_ involves "_duplicating_" the database to return results _faster_.
our objective should be to reduce time-to-results **_below_ 1 second** https://blog.kissmetrics.com/speed-is-a-killer/
_ideally_ availability should be a _separate_ lambda which runs after the results have been displayed in the UI (_initial result_) and updates then price/availability in the UI once the person is looking at the results. 
Currently the search results _are_ being cached in API Gateway for 5mins but we aren't checking how often the results _actually_ change...

**Comment by tomgco** [comment]
https://github.com/numo-labs/lambda-ne-dynamic-package-provider
