### ISSUE TITLE
Send Hotel Id to Client so we can pass it through to Analytics (Kinesis) ?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#108]
Last week we discussed what data we want to send in events to Kinesis, 
At present we're *constructing* the id of each package by combining `result.destinationCode + result.hotelCode`
see: https://github.com/numo-labs/lambda-ne-classic-package-provider/blob/8fc08051ba1bdffbaaba8d581838ddfc493a4d6f/lib/result_mapper.js#L114

We discussed using the `wvId` instead which would allow us to weight the hotels returned by Neo4J based on the number of clicks ... 

@tomgco / @lennym  is this still the plan?

**Comment by tomgco** [comment]
@nelsonic It certainly is :]

**Comment by nelsonic** [comment]
@tomgco should we name the property `package.hotelid` or re-purpose `package.id` ?

**Comment by tomgco** [comment]
@nelsonic I have been working on this issue at: https://github.com/numo-labs/lambda-ne-dynamic-package-provider/pull/1 and https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/109

**Comment by nelsonic** [comment]
Updated by @tomgco : https://github.com/numo-labs/lambda-ne-classic-package-provider/commit/2e2ad45ca954c7280015f17c8af883bfe40686f1
