### ISSUE TITLE
error parsing hotels from sns message

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#22]
![image](https://cloud.githubusercontent.com/assets/194400/14490154/2589da6a-0169-11e6-9882-8926d8321c93.png)
noted by @nikhilaravi

**Comment by nikhilaravi** [comment]
@nelsonic I think so! Have not seen this issue again since you fixed it

**Comment by nelsonic** [comment]
Cool. closing. 👍
