### ISSUE TITLE
Should we update this to use callback instead context.succeed/fail ?

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#52]
As the title suggests... should we update this to the latest format?

**Comment by hassy** [comment]
Yep, context.fail / succeed are deprecated I believe. The `0.10` runtime will be retired in October this year too.

**Comment by nelsonic** [comment]
@hassy feel free to update it tomorrow morning when you are adding `async.parallel` instead of the `forEach` ...

**Comment by lennym** [comment]
From the perspective of someone coming into this for the first time, and referring heavily to other lambdas when writing new things, I would be **very** strongly in favour of this.

**Comment by nelsonic** [comment]
@lennym agreed.
I don't mind doing it, but I know @hassy is working on the lambda right now and don't want to cause merge conflicts...

**Comment by hassy** [comment]
Cool, I'll start on that next

**Comment by hassy** [comment]
We have a couple of places using `failOnError` from `aws-lambda-helper`:

https://github.com/search?q=org%3Anumo-labs+failonerror&type=Code

Those will need to be updated as well, and the function should be removed altogether.

**Comment by nelsonic** [comment]
@hassy related but independent from *this* lambda.
I will remove the `failOnError` method, we are no longer using it.

**Comment by hassy** [comment]
yeah, thought I'd mention it while I'm at it

**Comment by hassy** [comment]
Fixed in https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/68
