### ISSUE TITLE
Send SNS message  Zero Package Results

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#91]
When there are no search results returned by the API, we need to *inform* the client.
So that "alternative" destinations can be shown to the person.
Relates to: https://github.com/numo-labs/isearch-ui/issues/227

**Comment by lennym** [comment]
This should be a message which is emitted when the package search is complete to indicate that no further results will be delivered. This will be irrespective of the number of results previously returned.
